avoid flaky test
ros2/system_tests pull request #513
Opened 2023-03-31 05:53 UTC by iuhilnehc-ynos

to fix https://github.com/ros2/rmw_cyclonedds/issues/440

refer to [ros2cli](https://github.com/ros2/ros2cli/blob/14e640c6060fcb191eee266c55bbf4bed6ac97db/ros2cli/ros2cli/helpers.py#L25) to implement a `wait_for`, and then wait to call the `get_subscriptions_info_by_topic` or `get_publishers_info_by_topic` by a timeout.

NOTE: keep the https://github.com/iuhilnehc-ynos/system_tests/blob/5b4ee6075a4a67ef7f8efbf27e0fcdf3adda6888/test_quality_of_service/test/test_best_available.cpp#L57-L68 and https://github.com/iuhilnehc-ynos/system_tests/blob/5b4ee6075a4a67ef7f8efbf27e0fcdf3adda6888/test_quality_of_service/test/test_best_available.cpp#L114-L125 because they do assert in the tests even if it's not the intention for the test name.

2023-03-31 09:36 UTC, iuhilnehc-ynos commented
CI:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18374)](http://ci.ros2.org/job/ci_linux/18374/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12912)](http://ci.ros2.org/job/ci_linux-aarch64/12912/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19045)](http://ci.ros2.org/job/ci_windows/19045/)

2023-04-03 12:53 UTC, clalancette requested changes
Minor change, but this was exactly the kind of thing I was thinking of.  Thanks!

2023-04-03 20:34 UTC, fujitatomoya approved these changes
lgtm with @clalancette comment applied.

2023-04-04 01:42 UTC, iuhilnehc-ynos commented
CI:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18410)](http://ci.ros2.org/job/ci_linux/18410/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12956)](http://ci.ros2.org/job/ci_linux-aarch64/12956/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19093)](http://ci.ros2.org/job/ci_windows/19093/)

2023-04-04 12:11 UTC, clalancette approved these changes

2023-04-04 12:11 UTC, merged