Add messages with key to test_communication
ros2/system_tests pull request #542
Opened 2024-04-03 08:40 UTC by MiguelCompany

This adds support for the messages added by ros2/rcl_interfaces#162 to the `test_communication` package

Depends on ros2/rosidl#796
Depends on ros2/rosidl_typesupport_fastrtps#116
Depends on ros2/rcl_interfaces#162

2024-09-19 16:36 UTC, fujitatomoya requested changes

2024-09-20 10:45 UTC, MiguelCompany commented on test_communication/CMakeLists.txt
> +    if(is_idl AND interface_ns STREQUAL "msg")
In a way, yes.
https://github.com/ros2/rcl_interfaces/pull/162 uncovered a bug in this `CMakeLists.txt` file.
The code here is not considering the case where a message is directly defined in a `.idl` file.

I suppose I could make a separate PR with the changes in 486acce7fbf8fcb2149f8fabb781c3c43e0dadae.

2024-09-20 10:51 UTC, MiguelCompany commented on test_communication/test/subscribe_key_types.cpp
> +// Copyright 2015 Open Source Robotics Foundation, Inc.
c01ad03cf1a117d9ebbb516c9698f0c453f2e500

2024-09-23 17:08 UTC, fujitatomoya commented on test_communication/CMakeLists.txt
> +    if(is_idl AND interface_ns STREQUAL "msg")
I guess we can fix this with another PR, so that we can backport this fix to other distros.

2024-09-24 06:48 UTC, MiguelCompany commented on test_communication/CMakeLists.txt
> +    if(is_idl AND interface_ns STREQUAL "msg")
See #549 for this.

2024-10-07 23:28 UTC, fujitatomoya commented on test_communication/CMakeLists.txt
> +    if(is_idl AND interface_ns STREQUAL "msg")
this can be removed from this PR after https://github.com/ros2/system_tests/pull/549 is merged

2025-04-03 05:52 UTC, MiguelCompany commented
Closed in favor of #568

2025-04-03 05:52 UTC, closed without merging