Update deprecated methods
ros2/system_tests pull request #546
Opened 2024-07-05 13:33 UTC by ahcorde

This API methods were deprecated on `jazzy` 

 - `https://github.com/ros2/rclcpp/blob/jazzy/rclcpp/include/rclcpp/waitable.hpp#L139-L143` https://github.com/ros2/rclcpp/blob/jazzy/rclcpp/include/rclcpp/waitable.hpp#L112-L116
 - `is_ready` https://github.com/ros2/rclcpp/blob/jazzy/rclcpp/include/rclcpp/waitable.hpp#L139-L143
 - execute https://github.com/ros2/rclcpp/blob/jazzy/rclcpp/include/rclcpp/waitable.hpp#L223-L227

This PR uses the right methods

2024-07-05 13:34 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21373)](http://ci.ros2.org/job/ci_linux/21373/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15680)](http://ci.ros2.org/job/ci_linux-aarch64/15680/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=883)](http://ci.ros2.org/job/ci_linux-rhel/883/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22109)](http://ci.ros2.org/job/ci_windows/22109/)

2024-07-08 22:35 UTC, clalancette requested changes
One minor thing to (maybe?) fix, then this looks good.

2024-07-08 22:35 UTC, clalancette commented on test_rclcpp/test/test_waitable.cpp
> +    rcl_ret_t ret = rcl_wait_set_add_timer(&const_cast<rcl_wait_set_t &>(wait_set),
At first glance, this looks suspicious.  We are taking an `rcl_wait_set_t &`, and then const-casting it to a `rcl_wait_set_t &`, and then taking the address of it.  But that seems unnecessary; can this be:

```suggestion
    rcl_ret_t ret = rcl_wait_set_add_timer(&wait_set,
```

2024-07-09 02:55 UTC, fujitatomoya reviewed
looks good to me after @clalancette 's comment is resolved.

2024-07-09 11:34 UTC, merged